databases:
  - name: cmsdb
    plan: free
    databaseName: cmsdb
    user: kruegenn

services:
  - type: web
    plan: free
    name: opencms
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn church.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cmsdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4