services:
  - type: web
    name: opencms  # Updated app name
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn church.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cmsdb-service # This connects to the database below
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "opencms.onrender.com"
      - key: PYTHON_VERSION
        value: "3.12.1"
      # Add your Cloudinary keys here or in the Render Dashboard
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
    postBuildCommand: |
      python manage.py migrate && \
      python scripts/setup_admin.py
      

databases:
  - name: cmsdb-service
    databaseName: cmsdb # The actual name inside Postgres
    plan: free