# Generated by Django 6.0.1 on 2026-03-18 04:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_rename_discipleshipgroup_fellowshipgroup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemorizeVerse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=10)),
                ('book_name', models.CharField(max_length=50)),
                ('chapter', models.PositiveSmallIntegerField()),
                ('verse_number', models.PositiveSmallIntegerField()),
                ('translation', models.CharField(choices=[('BSB', 'Berean Standard Bible'), ('KJV', 'King James Version'), ('NIV', 'New International Version'), ('ESV', 'English Standard Version'), ('NASB', 'New American Standard Bible')], default='BSB', max_length=10)),
                ('verse_text', models.TextField()),
                ('next_review', models.DateTimeField(default=django.utils.timezone.now)),
                ('interval_days', models.PositiveSmallIntegerField(default=1)),
                ('rep_count', models.PositiveIntegerField(default=0)),
                ('last_score', models.PositiveSmallIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memorize_verses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['next_review'],
                'unique_together': {('user', 'book_id', 'chapter', 'verse_number', 'translation')},
            },
        ),
        migrations.CreateModel(
            name='MemorizationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.PositiveSmallIntegerField(choices=[(1, 'Level 1 — every 4th word blanked'), (2, 'Level 2 — every other word blanked'), (3, 'Level 3 — first-letter hints'), (4, 'Level 4 — full recall')])),
                ('score', models.PositiveSmallIntegerField(choices=[(0, 'No recall'), (1, 'Partial recall'), (2, 'Recalled with effort'), (3, 'Perfect recall')])),
                ('verse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='mainapp.memorizeverse')),
            ],
            options={
                'ordering': ['-attempted_at'],
            },
        ),
    ]
