# Generated by Django 6.0.1 on 2026-03-24 09:22

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_readingplan_readingplanmember'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CharityOrganisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('banner', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image')),
                ('payment_method', models.CharField(choices=[('paypal', 'PayPal'), ('stripe', 'Stripe'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('cash', 'Cash'), ('other', 'Other')], default='bank_transfer', max_length=50)),
                ('donation_link', models.URLField(blank=True, help_text='External donation gateway URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.ManyToManyField(blank=True, related_name='charity_organisations', to=settings.AUTH_USER_MODEL)),
                ('pastor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='charity_organisations_led', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
