# Generated by Django 6.0.1 on 2026-03-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_charityorganisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charityorganisation',
            name='payment_method',
            field=models.TextField(blank=True, help_text='Payment details that congregants can use to donate'),
        ),
    ]
