# Generated by Django 6.0.1 on 2026-03-04 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0005_alter_comment_post'),
        ('communication', '0005_alter_comment_post_thread_replies'),
    ]

    operations = [
    ]
