# Generated by Django 6.0.1 on 2026-03-05 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0006_merge_20260304_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='author',
        ),
        migrations.DeleteModel(
            name='Replies',
        ),
        migrations.DeleteModel(
            name='Thread',
        ),
    ]
